/**
 * The authoring layer.
 *
 * Content is written here in one place — structure and English prose together — and split at
 * import time into the typed data the engine consumes and a flat English dictionary keyed by id.
 * Writing an event and forgetting its text is therefore not possible, and the keys are derived
 * rather than typed by hand, which removes the other half of the mistakes.
 *
 * Translations do not come back through here: a translator copies the generated key list and
 * writes `src/i18n/<locale>/`. English is simply the source language.
 */

import type {
  Choice,
  Condition,
  Department,
  DepartmentId,
  Effect,
  EventKind,
  GameEvent,
  InitiativeTemplate,
  Outcome,
  PlayerStats,
  QualityTier,
  TaskTemplate,
} from '../engine/types';

/** Every English string generated by the definitions below, keyed by its derived key. */
export const EN_STRINGS: Record<string, string> = {};

function register(key: string, text: string): string {
  if (EN_STRINGS[key] !== undefined && EN_STRINGS[key] !== text) {
    throw new Error(`Duplicate content key with different text: ${key}`);
  }
  EN_STRINGS[key] = text;
  return key;
}

/* ------------------------------------------------------------------ events */

export interface OutcomeSpec {
  /** Relative weight among this choice's outcomes. Defaults to 1. */
  weight?: number;
  text: string;
  effects?: Effect[];
  /** Restricts when this outcome can be rolled — see `Outcome.conditions`. */
  conditions?: Condition;
}

export interface ChoiceSpec {
  id: string;
  label: string;
  conditions?: Condition;
  /** Shorthand for a choice with a single certain outcome. */
  text?: string;
  effects?: Effect[];
  outcomes?: OutcomeSpec[];
}

export interface EventSpec {
  kind: EventKind;
  title: string;
  body: string;
  weight?: number;
  once?: boolean;
  cooldown?: number;
  conditions?: Condition;
  choices: ChoiceSpec[];
}

export function defineEvent(id: string, spec: EventSpec): GameEvent {
  const choices: Choice[] = spec.choices.map((choiceSpec) => {
    const specs: OutcomeSpec[] =
      choiceSpec.outcomes ??
      (choiceSpec.text !== undefined
        ? [{ text: choiceSpec.text, effects: choiceSpec.effects }]
        : []);

    if (specs.length === 0) {
      throw new Error(`Choice ${id}/${choiceSpec.id} has no outcome`);
    }

    const outcomes: Outcome[] = specs.map((outcome, index) => ({
      weight: outcome.weight ?? 1,
      textKey: register(`${id}.choice.${choiceSpec.id}.out.${index}`, outcome.text),
      effects: outcome.effects ?? [],
      conditions: outcome.conditions,
    }));

    return {
      id: choiceSpec.id,
      labelKey: register(`${id}.choice.${choiceSpec.id}`, choiceSpec.label),
      conditions: choiceSpec.conditions,
      outcomes,
    };
  });

  return {
    id,
    kind: spec.kind,
    titleKey: register(`${id}.title`, spec.title),
    bodyKey: register(`${id}.body`, spec.body),
    conditions: spec.conditions,
    weight: spec.weight ?? 10,
    once: spec.once,
    cooldown: spec.cooldown,
    choices,
  };
}

/* ------------------------------------------------------------------- tasks */

export interface TaskSpec {
  title: string;
  desc: string;
  departments: DepartmentId[] | 'any';
  minLevel?: number;
  maxLevel?: number;
  baseEffort: number;
  deadlineRange: [number, number];
  difficulty: 1 | 2 | 3;
  weight?: number;
  onComplete?: Partial<Record<QualityTier, Effect[]>>;
  onFail?: Effect[];
}

export function defineTask(id: string, spec: TaskSpec): TaskTemplate {
  return {
    id,
    titleKey: register(`${id}.title`, spec.title),
    descKey: register(`${id}.desc`, spec.desc),
    departments: spec.departments,
    minLevel: spec.minLevel,
    maxLevel: spec.maxLevel,
    baseEffort: spec.baseEffort,
    deadlineRange: spec.deadlineRange,
    difficulty: spec.difficulty,
    weight: spec.weight ?? 10,
    onComplete: spec.onComplete,
    onFail: spec.onFail,
  };
}

/* ------------------------------------------------------------- initiatives */

export interface InitiativeSpec {
  title: string;
  desc: string;
  /** Shown when it finally lands, years later. */
  complete: string;
  /** And when it is quietly dropped. */
  lapse: string;
  required: number;
  minCycles: number;
  available: Condition;
  onComplete: Effect[];
  onLapse?: Effect[];
}

/**
 * An undertaking the player may start.
 *
 * `onLapse` defaults to nothing rather than to a penalty. Most things quietly dropped in
 * government are quietly dropped without consequence, and a template that wants the opposite —
 * because somebody was promised something — says so explicitly.
 */
export function defineInitiative(id: string, spec: InitiativeSpec): InitiativeTemplate {
  return {
    id,
    titleKey: register(`${id}.title`, spec.title),
    descKey: register(`${id}.desc`, spec.desc),
    completeKey: register(`${id}.complete`, spec.complete),
    lapseKey: register(`${id}.lapse`, spec.lapse),
    required: spec.required,
    minCycles: spec.minCycles,
    available: spec.available,
    onComplete: spec.onComplete,
    onLapse: spec.onLapse ?? [],
  };
}

/* -------------------------------------------------------------- departments */

export interface DepartmentSpec {
  name: string;
  blurb: string;
  flavour: string;
  startingAdjustments: Partial<PlayerStats>;
}

export function defineDepartment(id: DepartmentId, spec: DepartmentSpec): Department {
  return {
    id,
    nameKey: register(`dept.${id}.name`, spec.name),
    blurbKey: register(`dept.${id}.blurb`, spec.blurb),
    flavourKey: register(`dept.${id}.flavour`, spec.flavour),
    startingAdjustments: spec.startingAdjustments,
  };
}

/* ------------------------------------------------------------------ generic */

/** Registers a plain string (endings, career titles, UI copy that lives beside content). */
export function text(key: string, value: string): string {
  return register(key, value);
}
