/**
 * The pool of names new staff are drawn from.
 *
 * These are literal strings rather than translation keys. They are proper nouns of people in a
 * fictional European state, and a Spanish edition should show the same colleagues, not translated
 * ones. Deliberately mixed in origin, because a public administration is.
 */
export const staffNames: string[] = [
  'Elena Marchetti',
  'Tomas Bergqvist',
  'Aisha Nkemelu',
  'Ruben Castellanos',
  'Margit Halvorsen',
  'Dario Petrescu',
  'Noor Haddad',
  'Katalin Varga',
  'Piet van Doorn',
  'Sofia Almeida',
  'Andrei Lungu',
  'Hélène Duquesne',
  'Marek Wiśniewski',
  'Ingrid Solberg',
  'Youssef Benali',
  'Clara Fontaine',
  'Bogdan Ilie',
  'Lucia Ferrara',
  'Jonas Aaltonen',
  'Amara Diallo',
  'Stefan Novak',
  'Beatriz Coelho',
  'Hannah Weiss',
  'Kristof Nagy',
  'Rosa Iglesias',
  'Viktor Anghel',
  'Maja Kovač',
  'Emile Rousseau',
  'Nadia Ferhat',
  'Oskar Lindqvist',
  'Teresa Marchetti',
  'Filip Dvořák',
  'Yasmin Kaya',
  'Gustav Ehrlich',
  'Paula Moreira',
  'Radu Stanescu',
  'Ines Delgado',
  'Matthias Brunner',
  'Zofia Lewandowska',
  'Karim Belhadj',
  'Anneke de Vries',
  'Lorenzo Bianchi',
  'Sanna Virtanen',
  'Petar Jovanović',
  'Camille Girard',
  'Dorota Zielińska',
  'Emeka Obi',
  'Silvia Contreras',
  'Henrik Dahl',
  'Leila Mansouri',
];
